Apply workaround for unresolved RSpec error
I don't know really why these 5 examples fail with RSpec 3.0, 3.1.
But I have noticed that splitting them allows to workaround the issue.

    Failure/Error: allow(subject).to receive(:handle_token_authentication_for)

    NoMethodError:
      undefined method `unbind' for #<Proc:0x00000004251080>

    # ./spec/lib/simple_token_authentication/
    #	acts_as_token_authentication_handler_spec.rb:51:in
    #   `block (4 levels) in <top (required)>'
    # ./spec/lib/simple_token_authentication/
    #   acts_as_token_authentication_handler_spec.rb:50:in
    #   `each'
    # ./spec/lib/simple_token_authentication/
    #   acts_as_token_authentication_handler_spec.rb:50:in
    #   `block (3 levels) in <top (required)>'

Observations:

 - the error seems to occur when an expectation and the action
   apply to the same object
 - I tried to allow() the expected methods without success
 - the affected spec examples are tagged with `rspec_3_error`